### ISSUE TITLE
Dashboard Courses Search Field

### ISSUE THREAD

**Issue by hashmich** [hashmich/DH-Registry#11]
A Filter for the courses listing in user's dashboards. 
filter by:

- users

- institutions

- ?

Free text searchbox?

Search within user's courses / all courses?

TODO: more exact specification. 
How is this feature different from the filters on the registry homepage?

**Comment by scholgew** [comment]
I think it would make sense to be able to search the various tables as a moderator/admin:
User
City
Institution
Course

Or a free full-text search field, perhaps? That may be the easiest...
