### ISSUE TITLE
Inform moderators about new courses

### ISSUE THREAD

**Issue by hashmich** [hashmich/DH-Registry#16]
Moderators should see a list of new courses on their dashboard for "approval". Freshly added courses will be visible, though, but there should be a mechanism to mark approved/reviewed courses.

**Comment by JinG28** [comment]
Hi! Your course list looks very good, but could you please also add DH courses from University College London? Here is the link of the MA/MSc in Digital Humanities http://www.ucl.ac.uk/dh/courses/mamsc

And other courses:
http://www.ucl.ac.uk/dh/courses

Thanks a lot! Please do let me know if you need more information. My email is jin.gao.13@ucl.ac.uk

Thanks!
Jin

**Comment by hashmich** [comment]
Moderators now get a message once, as a new course is published. 
The email contains the most important course details and some quicklinks to approve, edit or unpublish the course.
On the moderators dashboard, new courses are listed in a specific area. 
On approval, the course will just be marked as approved. Later changes are not supposed to undergo the approval process again. 
Moderators are currently not constantly reminded of new courses (would require a new cronjob)
