### ISSUE TITLE
Email for forgotten password never sent?

### ISSUE THREAD

**Issue by jilltxt** [hashmich/DH-Registry#31]
I have been receiving MANY email reminders to log in and update the registry of a DH course I added a while ago. However, I have forgotten my password, so have several times now requested a new password. The email with the link to change passwords never arrives. I have checked my spam filter, both in my email client and on the university server. Are the emails really be sent out?

**Comment by hashmich** [comment]
Dear Jill, those emails arrive in my inbox almost instantly. 
The only thing I can imagine are typos in your email. Will try to contact you this way...
