### ISSUE TITLE
New Field/ Filter / Taxonomy: Funding

### ISSUE THREAD

**Issue by hashmich** [hashmich/DH-Registry#5]
Clarin, DARIAH,...
TODO: create a list of entities

**Comment by scholgew** [comment]
I think that maybe an additional search field like "Framework" or "Infrastructure" would make sense, but we would need a more exhaustive list than just "CLARIN" and "DARIAH"... I am not quite sure how to find a good list for that (or who to ask)...

**Comment by hashmich** [comment]
Closed because of confusing it with the "DARIAH/CLARIN/Discipline Tagging" (also closed)
